name: dexdeform2
channels:
  - pytorch3d
  - iopath
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py39h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py39h06a4308_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_1
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py39
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.10.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_console=6.4.4=py39h06a4308_0
  - jupyter_core=5.2.0=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.5.3=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py39h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - nbclassic=0.5.2=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.2=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=22.0=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py39h6a678d5_2
  - pip=22.3.1=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - portalocker=2.7.0=py39hf3d152e_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.13=haa1d7c7_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.2=py39_cu113_pyt1100
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.4.0=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.3.2.post1=py39h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=py39h06a4308_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - tornado=6.2=py39h5eee18b_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing-extensions=4.4.0=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - wheel=0.38.4=py39h06a4308_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - addict==2.4.0
    - click==8.1.3
    - configargparse==1.5.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==4.4.2
    - flask==2.2.3
    - fonttools==4.38.0
    - imageio==2.25.1
    - imageio-ffmpeg==0.4.8
    - importlib-resources==5.12.0
    - itsdangerous==2.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.0
    - moviepy==1.0.3
    - nbformat==5.5.0
    - open3d==0.16.0
    - pandas==1.5.3
    - plotly==5.13.0
    - proglog==0.1.10
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - scikit-learn==1.2.1
    - scipy==1.10.1
    - tenacity==8.2.1
    - threadpoolctl==3.1.0
    - transforms3d==0.4.1
    - werkzeug==2.2.3
prefix: /home/sizheli/anaconda3/envs/dexdeform
